name: AdvancedKits
version: 1.0
description:
author: Cfil360
website: http://www.cfil360.com

main: com.cfil360.advancedkits.AdvancedKits
database: false

commands:
  kit:
   description: Basic kit command

permissions:
   kit.player:
     description: Gives access to use kits
   kit.admin:
     description: Gives access to all AdvancedKit commands
     default: op
