name: GameCore
version: 1.0
main: com.cfil360.gamecore.GameCore
author: cfil360
website: http://www.cfil360.com
description: A library for minigames

commands:
    Map:
        usage: /<command>
        description: Gather more info about the maps
        aliases: [m]
    Vote:
        usage: /<command> [map]
        description: Vote to play on a map
        aliases: [v]